Ajoute la page de profil et portfolio pour les utilisateurs et freela…
team-m2i/brikool-frontend pull request #2
Opened 2024-11-24 15:14 UTC by Aymane-Ennahli

Acceder a la route http://localhost:3000/fr/dashboard pour le test

Modifications : 
utilisation de template nextAdmin (https://nextjstemplates.com/templates/nextadmin)Docs :(https://docs.nextadmin.co/)

- Modification de tailwind.config.ts
- Ajout des nouveaux components 
-  Ajout de repertoire : src/css
-  Ajout de repertoire : src/fonts
- Ajout de repertoire : src/js
- Ajout de gook : src/hooks/useLocalStorage.tsx
- Ajout de hook : src/hooks/useColorMode.tsx
- Modication de : src/app/[locale]/dashboard/@freelancer/page.tsx
- Ajout de fichier : src/app/[locale]/dashboard/@freelancer/forms/form-elements/page.tsx
- Ajout de fichier : src/app/[locale]/dashboard/@freelancer/pages/settings/page.tsx

2024-11-24 16:43 UTC, codeonym requested changes
Address the following issues:

1. Dont use use client when not needed
2. Remove metadata from pages

2024-11-24 16:43 UTC, codeonym commented on src/app/[locale]/dashboard/@freelancer/forms/form-elements/page.tsx
> +
Remove metadata file -- i has already been edited on root layout

2024-11-24 16:43 UTC, codeonym commented on src/app/[locale]/dashboard/@freelancer/page.tsx
remove meta data from here

2024-11-24 16:43 UTC, codeonym commented on src/app/[locale]/dashboard/@freelancer/pages/settings/page.tsx
> +
remove metadata from here

2024-11-24 16:43 UTC, codeonym commented on src/components/Breadcrumbs/Breadcrumb.tsx
> +  return (
Create a segmented list of urls based on pathname ( seperation via '/')  
Notice: urls must be routable ( valid url within _Link_ component)

2024-11-24 16:43 UTC, codeonym commented on src/components/CalenderBox/index.tsx
> +const CalendarBox = () => {
Canlendar is hardcoded, better be removed

2024-11-24 16:43 UTC, codeonym commented on src/js/us-aea-en.js
Whats this file about?

2024-11-24 16:43 UTC, codeonym commented on tailwind.config.ts
dont chaange use as is , if there is a need to define a custom style add it to extention

2024-11-24 16:43 UTC, codeonym commented on src/components/Layouts/DefaultLaout.tsx
> +"use client";
dont use use-client in layout, and refactor the layout code to the nextjs special file: layout.tsx

2024-11-24 19:24 UTC, Aymane-Ennahli commented on src/app/[locale]/dashboard/@freelancer/forms/form-elements/page.tsx
> +
Done

2024-11-29 19:31 UTC, codeonym commented
Pull request cancelled due to code change

2024-11-29 19:31 UTC, closed without merging